// Code generated by ifacemaker; DO NOT EDIT.

package server

import (
	"context"
	"net/http"

	"github.com/labstack/echo/v4"
)

// ServerRepo ...
type ServerRepo interface {
	NewContext(req *http.Request, w http.ResponseWriter) Context
	RegisterRouters(group Kind, routers *RegisterRouters, middlewares ...MiddlewareFunc) error
	Start()
	GetEcho() *echo.Echo
	GetRouters() []*Route
	Close() error
	Shutdown(ctx context.Context) error
	GracefulShutdown() error
}
